language: rust

rust:
    - nightly
    - stable

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

os:
    - linux

before_install: rustup component add clippy rustfmt

before_script:
    - rustc --version
    - cargo --version

script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo clippy --all-targets -- -Dclippy::all
    - cargo fmt -- --check
    - cargo doc --verbose
